modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "banners4bm"
version = "${version}"
displayName = "Banners4BM"
authors = "nincodedo, djefrey"
description = '''
'''
logoFile = "assets/banners4bm/icon.png"

[[dependencies.banners4bm]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banners4bm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banners4bm]]
modId = "bluemap"
mandatory = true
versionRange = "[5.2,)"
ordering = "NONE"
side = "BOTH"
